version: '3'

services:
  postgres-db:
    image: postgres
    container_name: knowledge-base-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowledge
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - knowledge-network
    restart: always

  mongo-db:
    image: mongo
    container_name: knowledge-base-mongo
    environment:
      MONGO_INITDB_DATABASE: knowledge_stats
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - knowledge-network
    restart: always

networks:
  knowledge-network:
    driver: bridge

volumes:
  postgres-data:
  mongo-data:
